USDC Deployment
element-fi/elf-deploy pull request #57
Opened 2021-08-02 18:19 UTC by smmackey

2021-08-03 20:29 UTC, DannyDelott requested changes

2021-08-03 20:29 UTC, DannyDelott commented on addresses/frontend-mainnet.json
> +        "0x2d6e3515c8b47192ca3913770fa741d3c4dac354"
Minor capitalization nit: `0x2D6e3515C8b47192Ca3913770fa741d3C4Dac354`

2021-08-03 21:23 UTC, jrhea commented on addresses/frontend-mainnet.json
> +        "0x2d6e3515c8b47192ca3913770fa741d3c4dac354"
😱

2021-08-03 21:24 UTC, jrhea commented on addresses/mainnet.json
> +					"address": "0x2d6e3515c8b47192ca3913770fa741d3c4dac354",
```suggestion
					"address": "0x2D6e3515C8b47192Ca3913770fa741d3C4Dac354",
```

Capitalization nit

2021-08-03 21:25 UTC, jrhea commented on addresses/frontend-mainnet.json
> +        "0x2d6e3515c8b47192ca3913770fa741d3c4dac354"
```suggestion
        "0x2D6e3515C8b47192Ca3913770fa741d3C4Dac354"
```

2021-08-03 21:28 UTC, DannyDelott approved these changes

2021-08-04 17:39 UTC, jrhea approved these changes

2021-08-04 17:39 UTC, merged